/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package google_formfill;

public class App {
    public void getGreeting() throws InterruptedException, IOException {
        //TODO: call your test case functions one after other here
       // tests.testCase01();
        //END Tests
        // tests.endTest(); // End your test by clearning connections and closing browser

// uncomment for Google_formfill.java

         Google_formfill googleform = new Google_formfill();
         googleform.google_formfill();
         googleform.endTest();

    }
 
    public static void main(String[] args) throws InterruptedException, IOException {
        new App().getGreeting();
        
    }
    
}
